CREATE TABLE [dbo].[Mst_RecruitmentCandidate_Archive] (
    [RecruitmentCandidateArchiveId] INT            IDENTITY (1, 1) NOT NULL,
    [MarketingCompanyId]            INT            NOT NULL,
    [BadgeNo]                       NVARCHAR (50)  NULL,
    [FirstName]                     NVARCHAR (100) NOT NULL,
    [MiddleName]                    NVARCHAR (100) NULL,
    [LastName]                      NVARCHAR (100) NULL,
    [Dob]                           DATETIME       NULL,
    [Email]                         NVARCHAR (50)  NULL,
    [Nationality]                   NVARCHAR (50)  NULL,
    [PhoneNumber]                   NVARCHAR (50)  NULL,
    [RecruitmentCandidateId]        INT            NOT NULL,
    [Remark]                        NVARCHAR (MAX) NULL,
    [EducationLevel]                NVARCHAR (MAX) NULL,
    [RecruitmentType]               NVARCHAR (25)  NULL,
    [RecruiterBadgeNoOrName]        NVARCHAR (100) NULL,
    [RecruiterNote]                 NVARCHAR (MAX) NULL,
    [RecruitmentSource]             NVARCHAR (50)  NULL,
    [AdvertisementTitle]            NVARCHAR (50)  NULL,
    [AddressLine1]                  NVARCHAR (MAX) NULL,
    [AddressLine2]                  NVARCHAR (MAX) NULL,
    [AddressLine3]                  NVARCHAR (MAX) NULL,
    [AddressCity]                   NVARCHAR (MAX) NULL,
    [AddressPostCode]               NVARCHAR (MAX) NULL,
    [AddressState]                  NVARCHAR (100) NULL,
    [AddressCountry]                NVARCHAR (MAX) NULL,
    [EmergencyContactPerson]        NVARCHAR (MAX) NULL,
    [EmergencyContactRelationship]  NVARCHAR (MAX) NULL,
    [EmergencyContactPhoneNumber]   NVARCHAR (MAX) NULL,
    [Gender]                        NVARCHAR (6)   NULL,
    [Ic]                            NVARCHAR (30)  NULL,
    [BankName]                      NVARCHAR (200) NULL,
    [BankBranch]                    NVARCHAR (200) NULL,
    [BankAccountName]               NVARCHAR (100) NULL,
    [BankAccountNo]                 NVARCHAR (50)  NULL,
    [BankSwiftCode]                 NVARCHAR (50)  NULL,
    [PassportName]                  NVARCHAR (150) NULL,
    [PassportNo]                    NVARCHAR (30)  NULL,
    [PassportIssueDate]             DATETIME       NULL,
    [PassportExpiredDate]           DATETIME       NULL,
    [PassportIssueCountry]          NVARCHAR (50)  NULL,
    [Status]                        NVARCHAR (50)  NOT NULL,
    [IsTemporary]                   BIT            NOT NULL,
    [LocalFirstName]                NVARCHAR (255) NULL,
    [LocalLastName]                 NVARCHAR (50)  NULL,
    [IsPartime]                     BIT            NOT NULL,
    [TeamName]                      NVARCHAR (50)  NULL,
    [Nickname]                      NVARCHAR (100) NULL,
    [CountryRunningNumber]          INT            NOT NULL,
    [AccessCode]                    NVARCHAR (20)  NOT NULL,
    [IsDeleted]                     BIT            NOT NULL,
    [CreatedBy]                     NVARCHAR (50)  NULL,
    [CreatedDate]                   DATETIME       NULL,
    [UpdatedBy]                     NVARCHAR (50)  NULL,
    [UpdatedDate]                   DATETIME       NULL,
    [BankCountryCode]               VARCHAR (200)  NULL,
    [BAType]                        NVARCHAR (10)  NULL,
    CONSTRAINT [PK_dbo.Mst_RecruitmentCandidate_Archive] PRIMARY KEY CLUSTERED ([RecruitmentCandidateArchiveId] ASC)
);

