CREATE TABLE [dbo].[Mst_IndependentContractor_Archive] (
    [IndependentContractorArchiveId]  INT             IDENTITY (1, 1) NOT NULL,
    [BadgeNo]                         NVARCHAR (50)   NULL,
    [OriginalBadgeNo]                 NVARCHAR (50)   NULL,
    [OriginalIndependentContractorId] INT             NULL,
    [FirstName]                       NVARCHAR (100)  NOT NULL,
    [MiddleName]                      NVARCHAR (100)  NULL,
    [LastName]                        NVARCHAR (100)  NULL,
    [Gender]                          NVARCHAR (6)    NULL,
    [Ic]                              NVARCHAR (30)   NULL,
    [PassportName]                    NVARCHAR (150)  NULL,
    [PassportNo]                      NVARCHAR (30)   NULL,
    [PassportIssueDate]               DATETIME        NULL,
    [PassportExpiredDate]             DATETIME        NULL,
    [PassportIssueCountry]            NVARCHAR (50)   NULL,
    [Dob]                             DATETIME        NULL,
    [PhoneNumber]                     NVARCHAR (50)   NULL,
    [MobileNumber]                    NVARCHAR (50)   NULL,
    [Email]                           NVARCHAR (150)  NULL,
    [Nationality]                     NVARCHAR (50)   NOT NULL,
    [MarketingCompanyId]              INT             NOT NULL,
    [MarketingCompanyBranchId]        INT             NULL,
    [ReportBadgeNo]                   NVARCHAR (50)   NULL,
    [IndependentContractorLevelId]    INT             NOT NULL,
    [StartDate]                       DATETIME        NULL,
    [DateFirstOnField]                DATETIME        NULL,
    [LastSalesSubmissionDate]         DATETIME        NULL,
    [IndependentContractorId]         INT             NOT NULL,
    [EducationLevel]                  NVARCHAR (50)   NULL,
    [MaritalStatus]                   NVARCHAR (50)   NULL,
    [BirthPlace]                      NVARCHAR (50)   NULL,
    [PermanentAddress]                NVARCHAR (255)  NULL,
    [Beneficiary1]                    NVARCHAR (150)  NULL,
    [Beneficiary2]                    NVARCHAR (150)  NULL,
    [AddressLine1]                    NVARCHAR (150)  NULL,
    [AddressLine2]                    NVARCHAR (150)  NULL,
    [AddressLine3]                    NVARCHAR (150)  NULL,
    [AddressCity]                     NVARCHAR (80)   NULL,
    [AddressPostCode]                 NVARCHAR (20)   NULL,
    [AddressState]                    NVARCHAR (100)  NULL,
    [AddressCountry]                  NVARCHAR (30)   NULL,
    [EmergencyContactPerson]          NVARCHAR (150)  NULL,
    [EmergencyContactRelationship]    NVARCHAR (20)   NULL,
    [EmergencyContactPhoneNumber]     NVARCHAR (20)   NULL,
    [RecruitmentType]                 NVARCHAR (25)   NULL,
    [RecruiterBadgeNoOrName]          NVARCHAR (100)  NULL,
    [RecruiterNote]                   NVARCHAR (MAX)  NULL,
    [RecruitmentSource]               NVARCHAR (50)   NULL,
    [AdvertisementTitle]              NVARCHAR (50)   NULL,
    [BankName]                        NVARCHAR (200)  NULL,
    [BankBranch]                      NVARCHAR (200)  NULL,
    [BankAccountNo]                   NVARCHAR (50)   NULL,
    [BankAccountName]                 NVARCHAR (100)  NULL,
    [BankSwiftCode]                   NVARCHAR (50)   NULL,
    [TaxNumber]                       NVARCHAR (500)  NULL,
    [ReturnMaterialRemarks]           NVARCHAR (255)  NULL,
    [AppPassword]                     NVARCHAR (10)   NULL,
    [Status]                          NVARCHAR (MAX)  NOT NULL,
    [BondPercentage]                  DECIMAL (18, 2) NULL,
    [BondLimit]                       DECIMAL (18, 2) NULL,
    [ProfilePicture]                  NVARCHAR (MAX)  NULL,
    [BulletinPicture]                 NVARCHAR (MAX)  NULL,
    [RecruitmentCandidateId]          INT             NULL,
    [FirstAttemptScore]               NVARCHAR (50)   NULL,
    [FirstAttemptSubDate]             DATETIME        NULL,
    [SecondAttemptScore]              NVARCHAR (50)   NULL,
    [SecondAttemptSubDate]            DATETIME        NULL,
    [Nickname]                        NVARCHAR (100)  NULL,
    [PaymentSchema]                   NVARCHAR (50)   NULL,
    [TeamName]                        NVARCHAR (50)   NULL,
    [LocalFirstName]                  NVARCHAR (255)  NULL,
    [LocalLastName]                   NVARCHAR (50)   NULL,
    [Remark]                          NVARCHAR (MAX)  NULL,
    [IsStayBackTeam]                  BIT             NULL,
    [IsGoBackTeam]                    BIT             NULL,
    [EffectiveAdvancementDate]        DATETIME        NULL,
    [LastDeactivateDate]              DATETIME        NULL,
    [WithHoldingTax]                  FLOAT (53)      NULL,
    [Nhi]                             FLOAT (53)      NULL,
    [IsTemporary]                     BIT             NOT NULL,
    [IsPartime]                       BIT             NOT NULL,
    [IsDeleted]                       BIT             NOT NULL,
    [CreatedBy]                       NVARCHAR (50)   NULL,
    [CreatedDate]                     DATETIME        NULL,
    [UpdatedBy]                       NVARCHAR (50)   NULL,
    [UpdatedDate]                     DATETIME        NULL,
    [AgreementSignedDate]             DATETIME        NULL,
    [BankCountryCode]                 VARCHAR (200)   NULL,
    [SalesBranch]                     NVARCHAR (50)   NULL,
    [BAType]                          NVARCHAR (10)   NULL,
    [IsQREnabled]                     BIT             NULL,
    [ApplicationFormUrl]              NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_Mst_IndependentContractor_Archive] PRIMARY KEY CLUSTERED ([IndependentContractorArchiveId] ASC)
);

