CREATE TABLE [dbo].[Mst_CandidateApplication_Form1] (
    [CandidateApplicationForm1Id]        INT            IDENTITY (1, 1) NOT NULL,
    [RecruitmentCandidateId]             INT            NOT NULL,
    [FirstName]                          NVARCHAR (100) NULL,
    [MiddleName]                         NVARCHAR (100) NULL,
    [LastName]                           NVARCHAR (100) NULL,
    [NickName]                           NVARCHAR (100) NULL,
    [LocalFirstName]                     NVARCHAR (255) NULL,
    [LocalLastName]                      NVARCHAR (50)  NULL,
    [Ic]                                 NVARCHAR (30)  NULL,
    [Gender]                             NVARCHAR (6)   NULL,
    [Dob]                                DATETIME       NULL,
    [Nationality]                        NVARCHAR (50)  NULL,
    [MaritalStatus]                      NVARCHAR (MAX) NULL,
    [Email]                              NVARCHAR (150) NULL,
    [MobileNumber]                       NVARCHAR (MAX) NULL,
    [PhoneNumber]                        NVARCHAR (50)  NULL,
    [ResidentialAddress]                 NVARCHAR (MAX) NULL,
    [Country]                            NVARCHAR (30)  NULL,
    [State]                              NVARCHAR (50)  NULL,
    [City]                               NVARCHAR (80)  NULL,
    [Postcode]                           NVARCHAR (20)  NULL,
    [HasPassport]                        BIT            NULL,
    [HasCriminalConvictions]             BIT            NULL,
    [CriminalConvictionsDescription]     NVARCHAR (MAX) NULL,
    [ReasonForApplying]                  NVARCHAR (MAX) NULL,
    [BusinessGoals]                      NVARCHAR (MAX) NULL,
    [PersonalGoals]                      NVARCHAR (MAX) NULL,
    [NameOfInstituition]                 NVARCHAR (MAX) NULL,
    [HighestQualification]               NVARCHAR (MAX) NULL,
    [CourseName]                         NVARCHAR (MAX) NULL,
    [YearofGraduation]                   INT            NULL,
    [LanguageWriting]                    NVARCHAR (MAX) NULL,
    [LanguageSpeaking]                   NVARCHAR (MAX) NULL,
    [CurrentCompanyName]                 NVARCHAR (MAX) NULL,
    [CurrentCompanyPosition]             NVARCHAR (MAX) NULL,
    [CurrentCompanyPeriodofEmployment]   NVARCHAR (MAX) NULL,
    [CurrentCompanyLastofIncome]         NVARCHAR (MAX) NULL,
    [CurrentCompanyReasonofLeaving]      NVARCHAR (MAX) NULL,
    [PreviousCompany1Name]               NVARCHAR (MAX) NULL,
    [PreviousCompany1Position]           NVARCHAR (MAX) NULL,
    [PreviousCompany1PeriodofEmployment] NVARCHAR (MAX) NULL,
    [PreviousCompany1LastofIncome]       NVARCHAR (MAX) NULL,
    [PreviousCompany1ReasonofLeaving]    NVARCHAR (MAX) NULL,
    [PreviousCompany2Name]               NVARCHAR (MAX) NULL,
    [PreviousCompany2Position]           NVARCHAR (MAX) NULL,
    [PreviousCompany2PeriodofEmployment] NVARCHAR (MAX) NULL,
    [PreviousCompany2LastofIncome]       NVARCHAR (MAX) NULL,
    [PreviousCompany2ReasonofLeaving]    NVARCHAR (MAX) NULL,
    [Referee1Name]                       NVARCHAR (MAX) NULL,
    [Referee1ContacNumber]               NVARCHAR (MAX) NULL,
    [Referee1CompanyName]                NVARCHAR (MAX) NULL,
    [Referee1Designation]                NVARCHAR (MAX) NULL,
    [Referee2Name]                       NVARCHAR (MAX) NULL,
    [Referee2ContacNumber]               NVARCHAR (MAX) NULL,
    [Referee2CompanyName]                NVARCHAR (MAX) NULL,
    [Referee2Designation]                NVARCHAR (MAX) NULL,
    [FaceToFaceConfifdentDescription]    NVARCHAR (MAX) NULL,
    [BusinessOpportunityRate]            INT            NULL,
    [LearningOpportunityRate]            INT            NULL,
    [HighEarningRate]                    INT            NULL,
    [ChallengingProjectsRate]            INT            NULL,
    [RecognitionRate]                    INT            NULL,
    [LeadershipRate]                     INT            NULL,
    [CustomerServiceRate]                INT            NULL,
    [BankruptDescription]                NVARCHAR (MAX) NULL,
    [BusinessInvolvementDescription]     NVARCHAR (MAX) NULL,
    [SufferMedicalDescription]           NVARCHAR (MAX) NULL,
    [DateofAvailability]                 DATETIME       NULL,
    [ExpectedIncome]                     NVARCHAR (20)  NULL,
    [Status]                             NVARCHAR (MAX) NOT NULL,
    [IsDeleted]                          BIT            NOT NULL,
    [CreatedBy]                          NVARCHAR (50)  NULL,
    [CreatedDate]                        DATETIME       NULL,
    [UpdatedBy]                          NVARCHAR (50)  NULL,
    [UpdatedDate]                        DATETIME       NULL,
    [Referee1Type]                       VARCHAR (150)  NULL,
    [Referee2Type]                       VARCHAR (150)  NULL,
    [DateofCommenceWork]                 DATETIME       NULL,
    [MobileNumberHeader]                 NVARCHAR (255) NULL,
    [PhoneNumberHeader]                  NVARCHAR (255) NULL,
    [CurrentCompanyCurrency]             NVARCHAR (255) NULL,
    [CurrentCompanyIncomeType]           NVARCHAR (255) NULL,
    [PreviousCompany1Currency]           NVARCHAR (255) NULL,
    [PreviousCompany1IncomeType]         NVARCHAR (255) NULL,
    [PreviousCompany2Currency]           NVARCHAR (255) NULL,
    [Referee1ContacNumberPrefixCode]     NVARCHAR (255) NULL,
    [Referee2ContacNumberPrefixCode]     NVARCHAR (255) NULL,
    [ExpectedIncomeType]                 NVARCHAR (255) NULL,
    [ExpectedIncomeCurrency]             NVARCHAR (255) NULL,
    CONSTRAINT [PK_dbo.Mst_CandidateApplication_Form1] PRIMARY KEY CLUSTERED ([CandidateApplicationForm1Id] ASC),
    CONSTRAINT [FK_dbo.Mst_CandidateApplication_Form1_dbo.Mst_RecruitmentCandidate_RecruitmentCandidateId] FOREIGN KEY ([RecruitmentCandidateId]) REFERENCES [dbo].[Mst_RecruitmentCandidate] ([RecruitmentCandidateId])
);


GO
CREATE NONCLUSTERED INDEX [IX_RecruitmentCandidateId]
    ON [dbo].[Mst_CandidateApplication_Form1]([RecruitmentCandidateId] ASC);

