CREATE TABLE [dbo].[Mst_DigitalFormSettings] (
    [MarketingCompanyId]                 INT            NOT NULL,
    [FirstName]                          BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_FirstName] DEFAULT ((1)) NULL,
    [MiddleName]                         BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_MiddleName] DEFAULT ((1)) NULL,
    [LastName]                           BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_LastName] DEFAULT ((1)) NULL,
    [NickName]                           BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_NickName] DEFAULT ((1)) NULL,
    [LocalFirstName]                     BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_LocalFirstName] DEFAULT ((1)) NULL,
    [LocalLastName]                      BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_LocalLastName] DEFAULT ((1)) NULL,
    [Ic]                                 BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_Ic] DEFAULT ((1)) NULL,
    [Gender]                             BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_Gender] DEFAULT ((1)) NULL,
    [Dob]                                BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_Dob] DEFAULT ((1)) NULL,
    [Nationality]                        BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_Nationality] DEFAULT ((1)) NULL,
    [MaritalStatus]                      BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_MaritalStatus] DEFAULT ((1)) NULL,
    [Email]                              BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_Email] DEFAULT ((1)) NULL,
    [MobileNumber]                       BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_MobileNumber] DEFAULT ((1)) NULL,
    [PhoneNumber]                        BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_PhoneNumber] DEFAULT ((1)) NULL,
    [ResidentialAddress]                 BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_ResidentialAddress] DEFAULT ((1)) NULL,
    [Country]                            BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_Country] DEFAULT ((1)) NULL,
    [State]                              BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_State] DEFAULT ((1)) NULL,
    [City]                               BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_City] DEFAULT ((1)) NULL,
    [Postcode]                           BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_Postcode] DEFAULT ((1)) NULL,
    [HasPassport]                        BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_HasPassport] DEFAULT ((1)) NULL,
    [HasCriminalConvictions]             BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_HasCriminalConvictions] DEFAULT ((1)) NULL,
    [CriminalConvictionsDescription]     BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_CriminalConvictionsDescription] DEFAULT ((1)) NULL,
    [ReasonForApplying]                  BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_ReasonForApplying] DEFAULT ((1)) NULL,
    [BusinessGoals]                      BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_BusinessGoals] DEFAULT ((1)) NULL,
    [PersonalGoals]                      BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_PersonalGoals] DEFAULT ((1)) NULL,
    [NameOfInstituition]                 BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_NameOfInstituition] DEFAULT ((1)) NULL,
    [HighestQualification]               BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_HighestQualification] DEFAULT ((1)) NULL,
    [CourseName]                         BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_CourseName] DEFAULT ((1)) NULL,
    [YearofGraduation]                   BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_YearofGraduation] DEFAULT ((1)) NULL,
    [LanguageWriting]                    BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_LanguageWriting] DEFAULT ((1)) NULL,
    [LanguageSpeaking]                   BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_LanguageSpeaking] DEFAULT ((1)) NULL,
    [CurrentCompanyName]                 BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_CurrentCompanyName] DEFAULT ((1)) NULL,
    [CurrentCompanyPosition]             BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_CurrentCompanyPosition] DEFAULT ((1)) NULL,
    [CurrentCompanyPeriodofEmployment]   BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_CurrentCompanyPeriodofEmployment] DEFAULT ((1)) NULL,
    [CurrentCompanyLastofIncome]         BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_CurrentCompanyLastofIncome] DEFAULT ((1)) NULL,
    [CurrentCompanyReasonofLeaving]      BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_CurrentCompanyReasonofLeaving] DEFAULT ((1)) NULL,
    [PreviousCompany1Name]               BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_PreviousCompany1Name] DEFAULT ((1)) NULL,
    [PreviousCompany1Position]           BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_PreviousCompany1Position] DEFAULT ((1)) NULL,
    [PreviousCompany1PeriodofEmployment] BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_PreviousCompany1PeriodofEmployment] DEFAULT ((1)) NULL,
    [PreviousCompany1LastofIncome]       BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_PreviousCompany1LastofIncome] DEFAULT ((1)) NULL,
    [PreviousCompany1ReasonofLeaving]    BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_PreviousCompany1ReasonofLeaving] DEFAULT ((1)) NULL,
    [PreviousCompany2Name]               BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_PreviousCompany2Name] DEFAULT ((1)) NULL,
    [PreviousCompany2Position]           BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_PreviousCompany2Position] DEFAULT ((1)) NULL,
    [PreviousCompany2PeriodofEmployment] BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_PreviousCompany2PeriodofEmployment] DEFAULT ((1)) NULL,
    [PreviousCompany2LastofIncome]       BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_PreviousCompany2LastofIncome] DEFAULT ((1)) NULL,
    [PreviousCompany2ReasonofLeaving]    BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_PreviousCompany2ReasonofLeaving] DEFAULT ((1)) NULL,
    [Referee1Name]                       BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_Referee1Name] DEFAULT ((1)) NULL,
    [Referee1ContacNumber]               BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_Referee1ContacNumber] DEFAULT ((1)) NULL,
    [Referee1CompanyName]                BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_Referee1CompanyName] DEFAULT ((1)) NULL,
    [Referee1Designation]                BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_Referee1Designation] DEFAULT ((1)) NULL,
    [Referee2Name]                       BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_Referee2Name] DEFAULT ((1)) NULL,
    [Referee2ContacNumber]               BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_Referee2ContacNumber] DEFAULT ((1)) NULL,
    [Referee2CompanyName]                BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_Referee2CompanyName] DEFAULT ((1)) NULL,
    [Referee2Designation]                BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_Referee2Designation] DEFAULT ((1)) NULL,
    [FaceToFaceConfifdentDescription]    BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_FaceToFaceConfifdentDescription] DEFAULT ((1)) NULL,
    [BusinessOpportunityRate]            BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_BusinessOpportunityRate] DEFAULT ((1)) NULL,
    [LearningOpportunityRate]            BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_LearningOpportunityRate] DEFAULT ((1)) NULL,
    [HighEarningRate]                    BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_HighEarningRate] DEFAULT ((1)) NULL,
    [ChallengingProjectsRate]            BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_ChallengingProjectsRate] DEFAULT ((1)) NULL,
    [RecognitionRate]                    BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_RecognitionRate] DEFAULT ((1)) NULL,
    [LeadershipRate]                     BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_LeadershipRate] DEFAULT ((1)) NULL,
    [CustomerServiceRate]                BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_CustomerServiceRate] DEFAULT ((1)) NULL,
    [BankruptDescription]                BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_BankruptDescription] DEFAULT ((1)) NULL,
    [BusinessInvolvementDescription]     BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_BusinessInvolvementDescription] DEFAULT ((1)) NULL,
    [SufferMedicalDescription]           BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_SufferMedicalDescription] DEFAULT ((1)) NULL,
    [DateofAvailability]                 BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_DateofAvailability] DEFAULT ((1)) NULL,
    [ExpectedIncome]                     BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_ExpectedIncome] DEFAULT ((1)) NULL,
    [CreatedBy]                          NVARCHAR (100) NULL,
    [CreatedDate]                        DATETIME       NULL,
    [UpdatedBy]                          NVARCHAR (100) NULL,
    [UpdatedDate]                        DATETIME       NULL,
    [Referee1Type]                       BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_Referee1Type] DEFAULT ((1)) NULL,
    [Referee2Type]                       BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_Referee2Type] DEFAULT ((1)) NULL,
    [DateofCommenceWork]                 BIT            CONSTRAINT [DF_Mst_DigitalFormSettings_DateofCommenceWork] DEFAULT ((1)) NULL,
    [FormType]                           NVARCHAR (8)   NULL,
    [TriggerPoint]                       NVARCHAR (50)  NULL
);

