CREATE TABLE [dbo].[Reporting_Recruitment_Activity] (
    [RecruitmentCandidateId]            NVARCHAR (50)  NOT NULL,
    [RecruitmentCandidateActivityLogId] INT            NULL,
    [ActivityStage]                     NVARCHAR (50)  NULL,
    [ActivityDescription]               NVARCHAR (50)  NULL,
    [ActivityAppointment]               NVARCHAR (50)  NULL,
    [ActivityUnsuitableStatus]          NVARCHAR (50)  NULL,
    [ActivityNotSucceedReason]          NVARCHAR (50)  NULL,
    [ActivityScheduleStartDateTime]     DATETIME       NULL,
    [ActivityScheduleStartWeekending]   DATETIME       NULL,
    [ActivityScheduleEndDateTime]       DATETIME       NULL,
    [ActivityMarketingCompanyBranchId]  INT            NULL,
    [ActivityLocation]                  NVARCHAR (MAX) NULL,
    [ActivityLeaderBadgeNo]             NVARCHAR (MAX) NULL,
    [ActivityRemark]                    NVARCHAR (MAX) NULL,
    [ActivityCreatedDate]               DATETIME       NULL,
    [ActivityUpdatedDate]               DATETIME       NULL,
    [ActivityConductedBy]               NVARCHAR (250) NULL,
    [BadgeNo]                           NVARCHAR (50)  NULL,
    [FirstName]                         NVARCHAR (100) NOT NULL,
    [MiddleName]                        NVARCHAR (100) NULL,
    [LastName]                          NVARCHAR (100) NULL,
    [Dob]                               DATETIME       NULL,
    [Email]                             NVARCHAR (150) NULL,
    [Nationality]                       NVARCHAR (50)  NOT NULL,
    [PhoneNumber]                       NVARCHAR (50)  NULL,
    [IsDeleted]                         BIT            NOT NULL,
    [CreatedDate]                       DATETIME       NULL,
    [UpdatedDate]                       DATETIME       NULL,
    [Remark]                            NVARCHAR (MAX) NULL,
    [EducationLevel]                    NVARCHAR (50)  NULL,
    [RecruitmentType]                   NVARCHAR (25)  NULL,
    [RecruiterBadgeNoOrName]            NVARCHAR (100) NULL,
    [RecruiterNote]                     NVARCHAR (MAX) NULL,
    [RecruitmentSource]                 NVARCHAR (50)  NULL,
    [RecruitmentSubSource]              NVARCHAR (50)  NULL,
    [AdvertisementTitle]                NVARCHAR (50)  NULL,
    [AddressLine1]                      NVARCHAR (150) NULL,
    [AddressLine2]                      NVARCHAR (150) NULL,
    [AddressLine3]                      NVARCHAR (150) NULL,
    [AddressCity]                       NVARCHAR (80)  NULL,
    [AddressPostCode]                   NVARCHAR (20)  NULL,
    [AddressState]                      NVARCHAR (100) NULL,
    [AddressCountry]                    NVARCHAR (30)  NULL,
    [EmergencyContactPerson]            NVARCHAR (150) NULL,
    [EmergencyContactRelationship]      NVARCHAR (20)  NULL,
    [EmergencyContactPhoneNumber]       NVARCHAR (20)  NULL,
    [Gender]                            NVARCHAR (6)   NULL,
    [Ic]                                NVARCHAR (30)  NULL,
    [BankName]                          NVARCHAR (200) NULL,
    [BankBranch]                        NVARCHAR (200) NULL,
    [BankAccountName]                   NVARCHAR (100) NULL,
    [BankAccountNo]                     NVARCHAR (50)  NULL,
    [BankSwiftCode]                     NVARCHAR (50)  NULL,
    [PassportName]                      NVARCHAR (150) NULL,
    [PassportNo]                        NVARCHAR (30)  NULL,
    [PassportIssueDate]                 DATETIME       NULL,
    [PassportExpiredDate]               DATETIME       NULL,
    [PassportIssueCountry]              NVARCHAR (50)  NULL,
    [Nickname]                          NVARCHAR (100) NULL,
    [TeamName]                          NVARCHAR (50)  NULL,
    [LocalFirstName]                    NVARCHAR (255) NULL,
    [LocalLastName]                     NVARCHAR (50)  NULL,
    [IsPartime]                         BIT            NOT NULL,
    [IsTemporary]                       BIT            NOT NULL,
    [Status]                            NVARCHAR (50)  NOT NULL,
    [CountryRunningNumber]              INT            NOT NULL,
    [BankCountryCode]                   VARCHAR (200)  NULL,
    [MCId]                              INT            NOT NULL,
    [MCName]                            NVARCHAR (150) NULL,
    [MCCountry]                         NVARCHAR (10)  NULL,
    [MCStatus]                          NVARCHAR (10)  NULL,
    [ActivityGroupWeekending]           DATETIME       NULL,
    [TeamLeaderAdvanceDate]             DATETIME       NULL,
    [BAStartDate]                       DATETIME       NULL,
    [MCCode]                            NVARCHAR (10)  NULL
);

