CREATE TABLE [dbo].[TXN_HUDDLE_RPT] (
    [Country]           NVARCHAR (20)   NULL,
    [Division]          NVARCHAR (20)   NULL,
    [Customer]          NVARCHAR (50)   NULL,
    [Weekending]        DATE            NULL,
    [RMonth]            NVARCHAR (50)   NULL,
    [RQuarter]          NVARCHAR (50)   NULL,
    [GrossPiece]        INT             NOT NULL,
    [One Time Pieces]   INT             NOT NULL,
    [Reject Pieces]     INT             NOT NULL,
    [Resub Pieces]      INT             NOT NULL,
    [NetPiece]          INT             NOT NULL,
    [CountryUSHC]       INT             NULL,
    [DivUSCH]           INT             NULL,
    [USCH]              INT             NULL,
    [GrossSales]        DECIMAL (18, 2) NULL,
    [NewStarter]        INT             NULL,
    [Leaver]            INT             NULL,
    [CountryHC]         INT             NOT NULL,
    [CountryDivHC]      INT             NOT NULL,
    [CountryCampaignHC] INT             NOT NULL,
    [GrossBAEarning]    DECIMAL (18, 2) NOT NULL,
    [NetBAEarning]      DECIMAL (18, 2) NOT NULL,
    [SWBonus]           DECIMAL (18, 2) NOT NULL,
    [BuletinPoint]      DECIMAL (18, 2) NOT NULL,
    [RejectPieceOT]     INT             NOT NULL,
    [RejectPieceREC]    INT             NOT NULL,
    [ResubPieceOT]      INT             NOT NULL,
    [ResubPieceREC]     INT             NOT NULL
);

