CREATE TABLE [dbo].[TXN_Temp_Starhub_CPQ] (
    [Id]                    BIGINT           IDENTITY (1, 1) NOT NULL,
    [System_TransactionKey] UNIQUEIDENTIFIER NULL,
    [SubmissionDate]        DATE             NULL,
    [Reseller]              NVARCHAR (50)    NULL,
    [NewAccountType]        NVARCHAR (20)    NULL,
    [TypeOfContract]        NVARCHAR (20)    NULL,
    [RevenueFlag]           INT              NULL,
    [ProductName]           NVARCHAR (200)   NULL,
    [CompanyName]           NVARCHAR (200)   NULL,
    [BusinessRegNo]         NVARCHAR (50)    NULL,
    [Promotion]             NVARCHAR (50)    NULL,
    [MRCCurrency]           NVARCHAR (10)    NULL,
    [MRC]                   DECIMAL (18, 4)  NULL,
    [QuantityPaidMonths]    INT              NULL,
    [CCVCurrency]           NVARCHAR (10)    NULL,
    [CCV]                   DECIMAL (18, 4)  NULL,
    [OrderCreatedDate]      DATE             NULL,
    [OpportunityStatus]     NVARCHAR (100)   NULL,
    [OrderLastModifiedDate] DATE             NULL,
    [StarhubServiceID]      NVARCHAR (200)   NULL,
    [OpportunityNo]         NVARCHAR (30)    NULL,
    [OwnerDivision]         NVARCHAR (50)    NULL,
    [CPQOpportunity]        INT              NULL,
    [OrderAcceptanceDate]   DATE             NULL,
    [DateContractSigned]    DATE             NULL,
    [DateOrderSubmitted]    DATE             NULL,
    [CloseDate]             DATE             NULL,
    [PrimaryContact]        NVARCHAR (100)   NULL,
    [ContactEmail]          NVARCHAR (100)   NULL,
    [ContactOfficePhone]    NVARCHAR (20)    NULL,
    [Contact1]              NVARCHAR (40)    NULL,
    [Contact1Email]         NVARCHAR (100)   NULL,
    [NewAccountDate]        NVARCHAR (50)    NULL,
    [ExistingAccountDate]   NVARCHAR (50)    NULL,
    [CRDate]                NVARCHAR (50)    NULL,
    [OpportunityOwner]      NVARCHAR (150)   NULL,
    [ChannelPartner]        NVARCHAR (150)   NULL,
    [CreatedDate]           DATETIME         NULL,
    [CreatedBy]             NVARCHAR (50)    NULL,
    CONSTRAINT [PK__TXN_Temp_Star__3214EC07855F50F5] PRIMARY KEY CLUSTERED ([Id] ASC)
);

