CREATE TABLE [dbo].[TXN_AutoAdvancementResult] (
    [ScheduleWeekending]           DATE            NULL,
    [CountryCode]                  NVARCHAR (10)   NULL,
    [Weekending1]                  DATE            NULL,
    [BadgeNo]                      NVARCHAR (50)   NULL,
    [DirectReportBadgeNo]          NVARCHAR (50)   NULL,
    [BALink]                       NVARCHAR (MAX)  NULL,
    [BAStatus]                     NVARCHAR (50)   NULL,
    [IndependentContractorID]      INT             NULL,
    [IndependentContractorLevelId] INT             NULL,
    [BALevel]                      NVARCHAR (50)   NULL,
    [WEBALevel]                    NVARCHAR (50)   NULL,
    [PromotionDate1]               DATE            NULL,
    [BAPersonalSalesValue]         DECIMAL (18, 2) NULL,
    [BAPersonalPoint]              DECIMAL (18, 4) NULL,
    [BASubPcs]                     INT             NULL,
    [CriteriaSubPcs]               NVARCHAR (100)  NULL,
    [CriteriaTeamSizeLevel]        NVARCHAR (100)  NULL,
    [BAProvince]                   NVARCHAR (50)   NULL,
    [CriteriaProvince]             NVARCHAR (50)   NULL,
    [BASalesValue]                 DECIMAL (18, 2) NULL,
    [CriteriaSalesValue]           DECIMAL (18, 2) NULL,
    [BASalesPcs]                   INT             NULL,
    [CriteriaSalesPcs]             INT             NULL,
    [BATeamSize]                   INT             NULL,
    [CriteriaTeamSize]             INT             NULL,
    [BABulettinPoint]              DECIMAL (18, 4) NULL,
    [CriteriaBuletinPoint]         DECIMAL (18, 4) NULL,
    [BAFirstGenLeader]             INT             NULL,
    [CriterialFirstGenLeader]      INT             NULL,
    [Weekending2]                  DATE            NULL,
    [DirectReportBadgeNo2]         NVARCHAR (50)   NULL,
    [BALevel2]                     NVARCHAR (50)   NULL,
    [WEBALevel2]                   NVARCHAR (50)   NULL,
    [PromotionDate2]               DATE            NULL,
    [BALink2]                      NVARCHAR (MAX)  NULL,
    [BAStatus2]                    NVARCHAR (50)   NULL,
    [BAProvince2]                  NVARCHAR (50)   NULL,
    [BAPersonalSalesValue2]        DECIMAL (18, 2) NULL,
    [BAPersonalPoint2]             DECIMAL (18, 2) NULL,
    [BASubPcs2]                    INT             NULL,
    [CriteriaSubPcs2]              NVARCHAR (100)  NULL,
    [CriteriaTeamSizeLevel2]       NVARCHAR (100)  NULL,
    [CriteriaProvince2]            NVARCHAR (50)   NULL,
    [BASalesValue2]                DECIMAL (18, 2) NULL,
    [CriteriaSalesValue2]          DECIMAL (18, 2) NULL,
    [BASalesPcs2]                  INT             NULL,
    [CriteriaSalesPcs2]            INT             NULL,
    [BATeamSize2]                  INT             NULL,
    [CriteriaTeamSize2]            INT             NULL,
    [BABulettinPoint2]             DECIMAL (18, 4) NULL,
    [CriteriaBuletinPoint2]        DECIMAL (18, 4) NULL,
    [BAFirstGenLeader2]            INT             NULL,
    [CriterialFirstGenLeader2]     INT             NULL,
    [Week1Result]                  NVARCHAR (20)   NULL,
    [Week2Result]                  NVARCHAR (20)   NULL,
    [FinalResult]                  NVARCHAR (20)   NULL,
    [Remark]                       NVARCHAR (1000) NULL,
    [ScheduleBALevel]              NVARCHAR (100)  NULL,
    [IsDeleted]                    BIT             NULL,
    [CreatedDate]                  DATETIME        NULL,
    [UpdatedDate]                  DATETIME        NULL,
    [WE1HitLevelRequirement]       BIT             NULL,
    [WE2HitLevelRequirement]       BIT             NULL
);

